version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      dev-dependencies:
        patterns:
          - "pytest*"
          - "mypy"
          - "ruff"
          - "pre-commit"
          - "types-*"

  - package-ecosystem: "docker"
    directory: "/docker/dev"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/docker/prod"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
